apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: lachisenarath576259/react-hello:c78c2be47af3196fce1dc1dbd89d4219c54e70cd
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-app
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  template:
    spec:
      containers:
        - image: lachisenarath576259/react-hello:c78c2be47af3196fce1dc1dbd89d4219c54e70cd
