apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/react
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-react
  targetNamespace: default
